module "infrastructure" {
  source = "../.."

  aws_region                  = var.aws_region
  project_name                = var.project_name
  environment                 = var.environment
  vpc_cidr                    = var.vpc_cidr
  availability_zones          = var.availability_zones
  public_subnet_cidrs         = var.public_subnet_cidrs
  private_subnet_cidrs        = var.private_subnet_cidrs
  ecr_repository_name         = var.ecr_repository_name
  enable_nat_gateway          = var.enable_nat_gateway
  nat_gateway_strategy        = var.nat_gateway_strategy
  enable_flow_logs            = var.enable_flow_logs
  log_retention_days          = var.log_retention_days
  flow_logs_kms_key_arn       = var.flow_logs_kms_key_arn
  ecr_kms_key_arn             = var.ecr_kms_key_arn
  ecs_container_name          = var.ecs_container_name
  ecs_image_tag               = var.ecs_image_tag
  ecs_cpu                     = var.ecs_cpu
  ecs_memory                  = var.ecs_memory
  ecs_desired_count           = var.ecs_desired_count
  ecs_app_port                = var.ecs_app_port
  ecs_assign_public_ip        = var.ecs_assign_public_ip
  ecs_log_retention_days      = var.ecs_log_retention_days
  ecs_health_check_path       = var.ecs_health_check_path
  spring_profiles_active      = var.spring_profiles_active
  ecr_image_retention_count   = var.ecr_image_retention_count
  enable_github_oidc          = var.enable_github_oidc
  github_repository           = var.github_repository
  github_branch               = var.github_branch
  rds_backup_retention_period = var.rds_backup_retention_period
  rds_instance_class          = var.rds_instance_class
  rds_database_name           = var.rds_database_name
  rds_username                = var.rds_username
  rds_engine_version          = var.rds_engine_version
  tags                        = var.tags
}
