variable "aws_region" { type = string }
variable "project_name" { type = string }
variable "environment" { type = string }
variable "vpc_cidr" { type = string }
variable "availability_zones" { type = list(string) }
variable "public_subnet_cidrs" { type = list(string) }
variable "private_subnet_cidrs" { type = list(string) }
variable "nat_gateway_strategy" { type = string }
variable "enable_flow_logs" { type = bool }
variable "log_retention_days" { type = number }
variable "flow_logs_kms_key_arn" { type = string }
variable "tags" { type = map(string) }
variable "ecr_repository_name" { type = string }
variable "ecr_image_retention_count" { type = number }
variable "ecr_kms_key_arn" { type = string }
variable "eks_cluster_name" { type = string }
variable "eks_kubernetes_version" { type = string }
variable "eks_node_instance_types" { type = list(string) }
variable "eks_node_desired_size" { type = number }
variable "eks_node_min_size" { type = number }
variable "eks_node_max_size" { type = number }
variable "eks_enable_public_endpoint" { type = bool }
variable "eks_public_endpoint_cidrs" { type = list(string) }
variable "eks_cluster_log_types" { type = list(string) }
variable "eks_secrets_kms_key_arn" { type = string }
variable "eks_require_imdsv2" { type = bool }
variable "enable_github_oidc" { type = bool }
variable "github_repository" { type = string }
variable "github_branch" { type = string }
variable "rds_instance_class" { type = string }
variable "rds_database_name" { type = string }
variable "rds_username" { type = string }
variable "rds_password" {
  type      = string
  sensitive = true
}
variable "rds_engine_version" { type = string }
variable "rds_multi_az" { type = bool }
variable "rds_deletion_protection" { type = bool }
variable "rds_skip_final_snapshot" { type = bool }
variable "rds_enable_performance_insights" { type = bool }
variable "rds_enable_enhanced_monitoring" { type = bool }
variable "rds_monitoring_interval" { type = number }
variable "rds_cloudwatch_log_exports" { type = list(string) }
variable "rds_kms_key_arn" { type = string }
