spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    platform: mysql
  jpa:
    hibernate:
      ddl-auto: validate
    database: mysql
    show-sql: true
#    Use below for generating mysql schema
#    properties:
#      javax:
#        persistence:
#          schema-generation:
#            create-source: metadata
#            scripts:
#              action: create
#              create-target: kasperin_database_create.sql

