apiVersion: v1
kind: ConfigMap
metadata:
  name: inventory-management-config
data:
  SPRING_PROFILES_ACTIVE: prod
  SPRING_DATASOURCE_URL: jdbc:mysql://rds-prod-hostname.invalid:3306/inventory
