apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: inventory-management-prod
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP":80},{"HTTPS":443}]'
    alb.ingress.kubernetes.io/ssl-redirect: "443"
    alb.ingress.kubernetes.io/certificate-arn: ACM_CERTIFICATE_ARN_PLACEHOLDER
    alb.ingress.kubernetes.io/healthcheck-path: /swagger-ui.html
    alb.ingress.kubernetes.io/success-codes: "200-399"
spec:
  ingressClassName: alb
  rules:
    - host: inventory.example.invalid
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: inventory-management
                port:
                  number: 8080
