apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: inventory-management
spec:
  podSelector:
    matchLabels:
      app: inventory-management
  policyTypes:
    - Ingress
  ingress:
    - ports:
        - protocol: TCP
          port: 8080
